import unittest

from travel.support.haversine import obter_ponto_cardeal
from travel.main.cardinal_points import NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST, NORTHWEST


class TestHaversine(unittest.TestCase):

    def test_obter_ponto_cardeal_mesmo_ponto(self):
        self.assertEqual("", obter_ponto_cardeal((39.0, 0), (39.0, 0)))

    def test_obter_ponto_cardeal_mesma_longitude(self):
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (39.5, 0)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38.5, 0)))

    def test_obter_ponto_cardeal_mesma_latitude(self):
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39.0, 1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39.0, -1)))

    def test_obter_ponto_cardeal_diagonais(self):
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40.0, 0)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40.0, 0.1)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40.0, 0.2)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40.0, 0.3)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40.0, 0.4)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 0.5)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 0.6)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 0.7)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 0.8)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 0.9)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (40.0, 1)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (39.9, 1)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (39.8, 1)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (39.7, 1)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (39.6, 1)))
        self.assertEqual(NORTHEAST, obter_ponto_cardeal((39.0, 0), (39.5, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39.4, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39.3, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39.2, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39.1, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (39, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (38.9, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (38.8, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (38.7, 1)))
        self.assertEqual(EAST, obter_ponto_cardeal((39.0, 0), (38.6, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38.5, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38.4, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38.3, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38.2, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38.1, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 1)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 0.9)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 0.8)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 0.7)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 0.6)))
        self.assertEqual(SOUTHEAST, obter_ponto_cardeal((39.0, 0), (38, 0.5)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, 0.4)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, 0.3)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, 0.2)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, 0.1)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, 0)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, -0.1)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, -0.2)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, -0.3)))
        self.assertEqual(SOUTH, obter_ponto_cardeal((39.0, 0), (38, -0.4)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -0.5)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -0.6)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -0.7)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -0.8)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -0.9)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38, -1)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38.1, -1)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38.2, -1)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38.3, -1)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38.4, -1)))
        self.assertEqual(SOUTHWEST, obter_ponto_cardeal((39.0, 0), (38.5, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (38.6, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (38.7, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (38.8, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (38.9, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39.1, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39.2, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39.3, -1)))
        self.assertEqual(WEST, obter_ponto_cardeal((39.0, 0), (39.4, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (39.5, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (39.6, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (39.7, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (39.8, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (39.9, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -1)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -0.9)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -0.8)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -0.7)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -0.6)))
        self.assertEqual(NORTHWEST, obter_ponto_cardeal((39.0, 0), (40, -0.5)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40, -0.4)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40, -0.3)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40, -0.2)))
        self.assertEqual(NORTH, obter_ponto_cardeal((39.0, 0), (40, -0.1)))
